### ISSUE TITLE
Possible improvements.

### ISSUE THREAD

**Issue by Heriberto-Juarez** [mercadopago/card-payment-sample#5]
Hi everyone. 
I wanted to let you know that I had some issues setting up the repo, I cloned it and I placed my KEY and TOKEN in the right places. (Using the node.js server)

Now, I expected It would work right away but it wasn't. 

First thing I noticed is that the frontend was working but when I tried to make a payment I saw in the browser's dev tools that /process_payments was not going to the server, instead to file://path-to-frontend/process_payments, so now I knew that I had to use some HTTP server like apache or nginx but that was not the solution because now the request was going to localhost:80/process_payments. 

For me its obvious that the frontend takes the host as base URL, so I went to _index.js_ (inside the frontend folder) and specify the path to the API localhost:8080  (The node.js server code returns this when running npm start, it logs something like: The server is now running on Port 8080

Now the line that was: 
`fetch("/process_payment", {`
is now: 
`fetch("http://localhost:8080/process_payment", {`

Now we don't assume that the api is running at the same port and same host as the front-end. 

Is it solved now? 
Not yet.

Now when I made a test I found a very common message about CORS.
The quick solution for node.js app is to: 
1. Install cors
2. Add it to app 

**Terminal:** 
`npm i cors`

**server.js**
```
const cors = require("cors")
app.use(cors())

```

Done.  Now the example is working, I think this could be implemented by default so that other developers have less things to do to be able to test this repo.

**Comment by nicolassalvanes** [comment]
Hi @Heriberto-Juarez,

We apologize for the delay. The changes you made should not be necessary, because both parts of the example (frontend and API) are running in the same HTTP server.

However, we have recently uploaded a new version of the example and you could check if it is working properly now, without further modifications.
In case any problem persist, please write to us again.

Thanks for reaching us,

the Mercado Pago team.
